# Generated by Django 5.0.6 on 2024-05-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bios',
            new_name='bio',
        ),
    ]
