# Generated by Django 5.0.6 on 2024-07-03 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storystream',
            name='following',
        ),
        migrations.RemoveField(
            model_name='storystream',
            name='story',
        ),
        migrations.AlterField(
            model_name='storystream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storystream',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.story'),
        ),
    ]
