# Generated by Django 5.0.6 on 2024-07-03 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_storystream_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storystream',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.story'),
        ),
    ]
