# Generated by Django 5.0.6 on 2024-06-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_messages_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
